name: "Hedia - NPM Autobumper"
description: "Hedia's npm packages autobumper"
icon: "arrow-up-circle"
inputs:
  label: # [major, minor, patch]
    description: "Type of version bump"
    required: true
runs:
  using: "composite"
  steps:
    - name: Fetch latest version from NPM
      env:
        LABEL: ${{ toJson(INPUT_LABEL) }}
      run: |
        chmod +x ${{ github.action_path }}/bump-package-version.sh
        ./${{ github.action_path }}/bump-package-version.sh "$LABEL"
      shell: bash
